### ISSUE TITLE
Update to pdftotext 2.2.2 might have broken the export

### ISSUE THREAD

**Issue by neugartf** [blalop/bbva2pandas#4]
Just noticed that the bump of pdftotext to 2.2.2 seems to have led to a different string export. Probably this change https://github.com/jalan/pdftotext/blob/master/CHANGES.md#220---2021-08-15
We might want to think to have a fake bbva export as pdf to have an integration test here. :) 

I will have a look later this week.

**Comment by blalop** [comment]
Hi @neugartf !

I've not found this issue, might take a closer look. If I understood correctly, all we have to do is set the [physical flag](https://github.com/jalan/pdftotext/blob/master/pdftotext.cpp#L221-L222) when invoking pdftotext, in order to keep the old layout, right?

I do agree the lib is lacking in tests and in integration tests in particular :(

**Comment by neugartf** [comment]
Yeah, that should work! I will open a PR with a integration test :) Sorry for the wait!

**Comment by blalop** [comment]
Finally found this issue after upgrading to Ubuntu 22. I'm yet working on it, but physical flag seems to don't fix it. I'll be updating.

**Comment by blalop** [comment]
I was wrong, the physical flag made the fix. Fixed in release 1.1.1. Thanks a lot for your help @neugartf!
